### ISSUE TITLE
OC EFI ITLWM

### ISSUE THREAD

**Issue by gityasss** [XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4#12]
Hi XXCoreRangerX
first of all thank you for providing and sharing your EFI with us, in my case it's working great on my HP 840 G4 i5 7300u touch
I tried to inject ITLWM to make my stock Intel 8265 work but in vain I can't make it to boot
If you would mind and share with us a working EFI for Intel stock users would be great
Thank you in advance 
Have a good day

**Comment by gityasss** [comment]
hello XXCoreRangerX 
ApECID in config.plist is already set to 0 
i tried upgrading your opencore EFI with latest one and updated all kexts and added the AirportItlwm kext too 
but when i boot it gives me kernel panic like 
this OC grabbed zero system-id for SB this is not allowed
Halting on critical error
maybe i missed something as i dont have good knowledge in hackintosh 
i attached the EFI i upgraded to look on it 
please if you can upload en EFI with itlwm it would be great 
thank you in advance:
[EFI.zip](https://github.com/XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4/files/7374170/EFI.zip)
)

**Comment by XXCoreRangerX** [comment]
Alright, your EFI looks fine. Except that the kext order is wrong. You do NOT want to place any kext before Lilu and VirtualSMC. That's the reason your laptop doesn't boot.

Try this EFI:
[EFI.zip](https://github.com/XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4/files/7374490/EFI.zip)
