### ISSUE TITLE
840 G7 

### ISSUE THREAD

**Issue by Pythnlearner** [XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4#14]
Will it work on HP elitebool 840 G7 i7

**Comment by XXCoreRangerX** [comment]
Hi, unfortunately the EFI is not going to work on an HP EliteBook 840 G7, because it has a much newer gen CPU. There's probably many other differences between G4 and G7 too.
I suggest you check out other EFIs or try making your own EFI.

**Comment by Pythnlearner** [comment]
I have working hackintosh in 840 G7 but unfortunately my touchpad is still not working..

**Comment by XXCoreRangerX** [comment]
Please follow [Dortania's OC Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html). Your laptop has a 10th gen CPU, while the G4 has a 7th gen CPU. There may be significant differences in the patches, SSDTs and kexts you need to use.

As for the touchpad, you should first check what connection type does it use. You can do that on Windows using [this](https://dortania.github.io/OpenCore-Install-Guide/find-hardware.html#keyboard-trackpad-and-touchscreen-connection-type) method or in a Linux command line:
```
dmesg | grep -i input
```
Based on that, again, follow the [guide](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#laptop-input) and use the required kexts.

**Comment by Pythnlearner** [comment]
Thank you for the information..I will definitely try and let you know.

**Comment by Pythnlearner** [comment]
I have also tried out one EFI made for   same model.. from https://github.com/yusfklncc/HP-EliteBook-840-G7-Hackintosh/release

But it gets stuck at: 
 [EB|#LOG:EXITBS:START]

**Comment by Pythnlearner** [comment]
I have attached details of my touchpad , will you help me to find right kexts with exact order? do I need to change any information in SSDT or info.plist
![Touchpad details](https://user-images.githubusercontent.com/66311873/146514145-bb334ec7-66db-4fc7-88c5-b74f1c009308.jpg)
![touchpad details2](https://user-images.githubusercontent.com/66311873/146514156-8428831c-35a8-4312-bc5e-961f0f73dc60.png)

.

**Comment by Pythnlearner** [comment]
Thank you for your support.. it really helpful.. and it worked.
