### ISSUE TITLE
Why not using RealtekCardReader.kext ,RealtekCardReaderFriend.kext

### ISSUE THREAD

**Issue by chris1111** [XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4#15]
[RealtekCardReader RealtekCardReaderFriend](https://github.com/0xFireWolf/RealtekCardReader)

I have the same laptop
See Screen Shot

![Screenshot 2022-07-01 at 11 25 33 AM](https://user-images.githubusercontent.com/6248794/176924148-9d31d9bc-d903-4dbd-a28f-96a0d00ccaf7.png)

**Comment by XXCoreRangerX** [comment]
Hello, thanks a lot for creating this issue.
I have tested the kext you mentioned and everything seems to be stable (in fact it's much more stable than `Sinetek-rtsx`). I'll update the EFI with this kext enabled.

**Comment by chris1111** [comment]
> Hello, thanks a lot for creating this issue. I have tested the kext you mentioned and everything seems to be stable (in fact it's much more stable than `Sinetek-rtsx`). I'll update the EFI with this kext enabled.

The only problem its about Sleep or Login Logout,  the SD card is ejected and for now no solution is find to fix that.
