### ISSUE TITLE
USB 3.0 Type C not working

### ISSUE THREAD

**Issue by DomiDomian** [XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4#2]
The USB Type C Port is not working with your mapped USBPorts.kext. I replaced it with USBinjectall.kext and now all is good. I will attach the kext here
[USBInjectAll.kext.zip](https://github.com/XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4/files/6018011/USBInjectAll.kext.zip)

**Comment by DomiDomian** [comment]
you also can use my mapped usbports.kext. its mapped with my hama USB-C hub
![Screen Shot 2021-02-21 at 17 02 04](https://user-images.githubusercontent.com/79382625/108630754-b2c9fc00-7466-11eb-9a66-f6a72e0637a2.png)
[USBPorts.kext.zip](https://github.com/XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4/files/6018021/USBPorts.kext.zip)

**Comment by XXCoreRangerX** [comment]
Hey, thanks for making a custom USB map kext.

Unfortunately I don't have any USB-C devices to test it with, so I didn't map it at all.

In your kext there are entries for all the ports, even for those which should be removed from it. The connector types are all USB3, while some should be set as internal, USB2 or USB-C. That might make some USB devices not work properly.

**Comment by DomiDomian** [comment]
ok thanks i think now i got it, but also in the past i never had problems with usb, just was using usbinjectall, but now its mapped
![Screen Shot 2021-02-21 at 21 48 18](https://user-images.githubusercontent.com/79382625/108638288-c25d3b00-748e-11eb-814a-e648898b7578.png)
[USBPorts.kext.zip](https://github.com/XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4/files/6018453/USBPorts.kext.zip)

**Comment by XXCoreRangerX** [comment]
HS labeled devices are never USB3. They are either Internal, USB-C or USB2. For me HS07 has to be set as Internal, for the bluetooth to work properly.

**Comment by XXCoreRangerX** [comment]
Hey, I included your work in the new `USBMap.kext`, and now it should all be working properly. You can download the [latest release](https://github.com/XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4/releases/tag/1.1.2) to use it. If there's any problems with it, create a new issue and I'll work on it. I'm closing this issue, because I had a friend test it and it works perfectly for him.

**Comment by DomiDomian** [comment]
great!
