### ISSUE TITLE
sorry friend, my account was suspended

### ISSUE THREAD

**Issue by DomiDomian** [XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4#4]
Hi, just wanted to tell you that I am back again. don't know why but my git account was suspended and now I am back again.

**Comment by XXCoreRangerX** [comment]
Yeah, I was wondering what happened. Glad to hear back from you.

**Comment by XXCoreRangerX** [comment]
I changed some things in the EFI and made some improvements. I also found a way to use the Wi-Fi button (still working on the LED). You can download the latest release and use new tweaks that I talk about in the README.
