### ISSUE TITLE
ACPI Patch for newer Bios

### ISSUE THREAD

**Issue by DomiDomian** [XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4#7]
ACPI Patch is not needed if you have SSDT-SET-STAS.aml in your ACPI Folder. I just disabled it in the config.

**Comment by XXCoreRangerX** [comment]
Sorry, turns out it was my wrong interpretation of [this](https://github.com/kecinzer/hpelitebook850g5-opencore/commit/65338feaa5d3cd005f8ba19ecc5250816d44d776) commit. I'll remove the unnecessary patch.
