### ISSUE TITLE
Updating OpenCore

### ISSUE THREAD

**Issue by DomiDomian** [XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4#8]
Hi I updated successfully to OpenCore 0.68 and some kexts , I had to make minor changes to input settings and cursor,  now it works. My Problem is that all the software (Hackintool, KextUpdater) does not recognise OpenCore 068, it still says that I am at 0.66. maybe there is a setting in config.plist for it?

**Comment by XXCoreRangerX** [comment]
Hey, I’m facing the same issue on my laptop. You could try resetting NVRAM, but it didn’t work for me. A lot of people are reporting this problem.

**Comment by DomiDomian** [comment]
yes I tried resetting nvram, always the same but I am definitely on OpenCore 0.68,  I will try later on my other HP. so far after a long time using your EFI I have to say it's really perfect and absolute stable. I am using it for Laser machine programming and processing, never had any issue with it ;)

**Comment by XXCoreRangerX** [comment]
Thanks for the feedback! Appreciate it a lot.

**Comment by XXCoreRangerX** [comment]
I'll close this issue, it's an OpenCore problem causing the version to display incorrectly.
